language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt -- --check
  - touch ./src/lib.rs && cargo clippy -- -D warnings
  - cargo test
